CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS referenti (
  code TEXT PRIMARY KEY, nome TEXT NOT NULL, wa TEXT NOT NULL DEFAULT '', tk TEXT NOT NULL UNIQUE,
  quota REAL, pos INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS preparatori (
  code TEXT PRIMARY KEY, nome TEXT NOT NULL, tk TEXT NOT NULL UNIQUE, pos INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS ordini (
  id TEXT PRIMARY KEY, anno TEXT NOT NULL, data TEXT NOT NULL,
  nome TEXT NOT NULL, cognome TEXT NOT NULL, telefono TEXT NOT NULL DEFAULT '',
  ref TEXT NOT NULL DEFAULT '', contatto TEXT NOT NULL DEFAULT '',
  q1 INTEGER NOT NULL DEFAULT 0, q3 INTEGER NOT NULL DEFAULT 0, q5 INTEGER NOT NULL DEFAULT 0, q10 INTEGER NOT NULL DEFAULT 0,
  kg REAL NOT NULL DEFAULT 0, euro REAL NOT NULL DEFAULT 0, note TEXT NOT NULL DEFAULT '',
  pagato INTEGER NOT NULL DEFAULT 0, consegnato INTEGER NOT NULL DEFAULT 0,
  costo REAL NOT NULL DEFAULT 0, ricarico REAL NOT NULL DEFAULT 0,
  r1 INTEGER NOT NULL DEFAULT 0, r3 INTEGER NOT NULL DEFAULT 0, r5 INTEGER NOT NULL DEFAULT 0, r10 INTEGER NOT NULL DEFAULT 0,
  pronto_dal TEXT NOT NULL DEFAULT '', prep_by TEXT NOT NULL DEFAULT '', pos INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS ordini_anno ON ordini(anno);
CREATE TABLE IF NOT EXISTS rids (rid TEXT PRIMARY KEY, res TEXT NOT NULL, ts INTEGER NOT NULL);
